EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "CUBFinal"
  SEED: 0
  CHECKPOINT_NAME: "mlp"
  TEXT_PROMPTS: ['a painting of a {} bird.']
  NEUTRAL_TEXT_PROMPTS: ['a photo of a {} bird.']
  EPOCHS: 200
  CHECKPOINT_VAL: True

DATA:
  DATASET: "CUB"
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    CHECKPOINT: 'checkpoint/mlp.pth'
    CHECKPOINT_NAME: 'CUB/mlp'
    RESUME: False

  USE_DOM_GT: False