EXP:
  ADVICE_METHOD: "Noop"
  WANDB_SILENT: False
  PROJ: "Debug_Directional"
  SEED: 0
  # TEXT_PROMPTS: [["clipart"], ["painting"], ["real photo"]]
  # TEXT_PROMPTS: [['painting']]
  TEXT_PROMPTS: [['a painting of an object.']]
  NEUTRAL_TEXT_PROMPTS: [['a sketch of an object.']]
  AUGMENTATION: 'Directional'
  EPOCHS: 200
  LOG_HIST: True
  
  
DATA:
  DATASET: "DomainNetMini"
  LOAD_CACHED: True

METHOD:
  MODEL:
    NUM_LAYERS: 2
    DOM_WEIGHT: 1.0
    LR: 0.001
    CHECKPOINT: 'checkpoint/mlp_simple.pth'
    CHECKPOINT_NAME: 'DomainNetMini/mlp-directional'
    RESUME: False
  USE_DOM_GT: True

AUGMENTATION:
  MODEL:
    LR: 0.0005
    WEIGHT_DECAY: 0.005
    NUM_LAYERS: 1
  EPOCHS: 10
  GENERIC: True
  ALPHA: 0.5