EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "DomainNetMiniFinal"
  SEED: 0
  CHECKPOINT_NAME: "mlp"
  TEXT_PROMPTS: ['clipart of a {}.', 'a painting of a {}.', 'a realistic photo of a {}.']
  EPOCHS: 200

DATA:
  DATASET: "DomainNetMini"

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    CHECKPOINT: 'checkpoint/mlp.pth'
    CHECKPOINT_NAME: 'DomainNetMini/mlp_debias'
    RESUME: False

  USE_DOM_GT: False