EXP:
  ADVICE_METHOD: "Noop"
  WANDB_SILENT: False
  PROJ: "CLIPAdvice"
  SEED: 0
  TEXT_PROMPTS: ["a photo of a {}."]
  NEUTRAL_TEXT_PROMPTS: []
  TEMPLATES: "imagenet"
  CHECKPOINT_VAL: True
  BIASED_VAL: True
  LOG_HIST_ONLY: False
  LOG_HIST: True
  CLIP_MODEL: 'ViT-L/14'
  IMAGE_FEATURES: 'clip'
  AUGMENTATION: None
  TRANSFORM_TEST: True
  ENSAMBLE: True
  CLIP_PRETRAINED_DATASET: 'openai'
  LOG_EMB_DRIFT: False

DATA:
  DATASET: "Waterbirds95"
  BATCH_SIZE: 256
  LOAD_CACHED: False
  UPWEIGHT_CLASSES: True
  UPWEIGHT_DOMAINS: True
  MODEL_DIM: 1024

METHOD:
  MODEL:
    WEAK_LABELS: False 
    NUM_LAYERS: 1
    LR: 0.001
    SEPERATE_CLASSES: True
    RESUME: False
    CHECKPOINT: './checkpoint/mlp_test.sav'
    CHECKPOINT_NAME: 'ColoredMNISTSimple/mlp'
    WEIGHT_DECAY: 0.05
    HIDDEN_DIM: 384
  NORMALIZE: True
  USE_DOM_GT: False
  C: None
  APPLY_TRANSFORMATION: "Noop"
  ALPHA: 0.5
  INCLUDE_ORIG_TRAINING: True
  NORMALIZE_OUTPUT: True

AUGMENTATION:
  MODEL:
    LR: 0.005
    WEIGHT_DECAY: 0.05
    HIDDEN_DIM: 384
    NUM_LAYERS: 2
  LOSS_TYPE: 'cosine'
  EPOCHS: 50
  GENERIC: False
  ALPHA: 0.5
  INCLUDE_ORIG_TRAINING: True
  TEST_TIME_AUG: False
  CLIP_NN_LOSS: False
  NN_CLASS_SPECIFIC: False
  COMPARE_BEFORE_AUG: True
  NN_INCLUDE_SAMPLE: True
  DOM_WEIGHT: 1.0
  DOM_SPECIFIC_XE: False
  DOM_LABELS: []
  CS_LOSS: False
  NN_WEIGHT: 0.0
  RANDOMIZE_PROB: 1.0
  RANDOMIZE: False
  REG_WEIGHT: 0.1
  CC_WEIGHT: 1.0
  CYCLE_GAN_WEIGHT: 0.0