EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "ColoredMNIST_ViT_Final"
  SEED: 0
  TEXT_PROMPTS: [['a photo of a red number.'], ['a photo of a blue number.']]
  AUGMENTATION: 'BiasDirectional'
  EPOCHS: 200
  LOG_HIST: False
  CHECKPOINT_VAL: True
  ENSAMBLE: False

  # CLIP_MODEL: 'ViT-H-14'
  # CLIP_PRETRAINED_DATASET: 'laion2b_s32b_b79k'
  # IMAGE_FEATURES: 'openclip'

DATA:
  DATASET: "ColoredMNISTBinary"
  LOAD_CACHED: True
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT: 'checkpoint/mlp_simple.pth'
    CHECKPOINT_NAME: 'DomainNetMini/mlp-directional'
    RESUME: False
    HIDDEN_DIM: 512
  USE_DOM_GT: False

AUGMENTATION:
  MODEL:
    HIDDEN_DIM: 512
  ALPHA: 1
  EPOCHS: 50
  GENERIC: True
  DOM_SPECIFIC_XE: False
  CLIP_NN_LOSS: True
  NN_WEIGHT: 0.1
  DOM_WEIGHT: 10
  REG_WEIGHT: 0.1
  CYCLE_GAN_WEIGHT: 0