EXP:
  ADVICE_METHOD: "CLIPZS"
  WANDB_SILENT: False
  PROJ: "ColoredMNIST_ViT_Final"
  SEED: 0
  TEXT_PROMPTS: ['0','1','2','3','4','5','6','7','8','9']
  TEMPLATES: 'color_mnist_templates'
  # TEMPLATES: 'no_template'
  
DATA:
  DATASET: "ColoredMNISTBinary"
  LOAD_CACHED: True
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    SEPERATE_CLASSES: True
    RESUME: True
  NORMALIZE: False