EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "Waterbirds_ViT14"
  SEED: 0
  TEXT_PROMPTS: ['a photo of a {} on forest.', 'a photo of a {} on water.']
  NEUTRAL_TEXT_PROMPTS: []
  AUGMENTATION: 'BiasDirectional'
  EPOCHS: 200
  LOG_HIST: True
  CHECKPOINT_VAL: True
  ENSAMBLE: False
  
  
DATA:
  DATASET: "Waterbirds"
  LOAD_CACHED: True
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT: 'checkpoint/mlp_simple.pth'
    CHECKPOINT_NAME: 'mlp-directional'
    RESUME: False
  # USE_DOM_GT: True

AUGMENTATION:
  MODEL:
    LR: 0.005
    WEIGHT_DECAY: 0.05
    NUM_LAYERS: 1
    HIDDEN_DIM: 512
  EPOCHS: 50
  GENERIC: False
  DOM_LABELS: ['forest', 'water']
  DOM_SPECIFIC_XE: True
  ALPHA: 0.75
  CLIP_NN_LOSS: True
  COMPARE_BEFORE_AUG: True
  NN_INCLUDE_SAMPLE: True
  DOM_WEIGHT: 1.0
  NN_WEIGHT: 1.0