EXP:
  ADVICE_METHOD: "CLIPZS"
  WANDB_SILENT: False
  PROJ: "LADS_Waterbirds_Rebuttal"
  SEED: 0
  TEXT_PROMPTS: ['landbird', 'waterbird']
  # TEMPLATES: 'no_template'
  TEMPLATES: 'waterbirds_templates2'
  
DATA:
  DATASET: "Waterbirds"
  BATCH_SIZE: 256
  LOAD_CACHED: True
  UPWEIGHT_CLASSES: True

METHOD:
  MODEL:
    NUM_LAYERS: 1
    SEPERATE_CLASSES: True
    RESUME: True
  NORMALIZE: False